### ISSUE TITLE
Staging cluster

### ISSUE THREAD

**Issue by predrag-rakic** [adnanrahic/boilerplate-api#34]
https://github.com/adnanrahic/boilerplate-api/blob/e0a656bdfde0ff56cbd4fa8ce9c34959cc239b80/.semaphore/push-images.yml#L50

What is the purpose of this cluster?
All green builds are automatically deployed in it, so my question is what is actually going on in there.

**Comment by adnanrahic** [comment]
In the scenario of when you have a staging cluster for deploying every version of the application. A use-case for this could be to create a test cluster for every pull request for a human to approve the version for production. This step is not needed, but a cool feature. I'd remove this section altogether because it's not necessary for the end goal.

**Comment by predrag-rakic** [comment]
It can be useful I agree.
But the way promotion was configured is to deploy _every_ green build, regardless of branch it is on.
Which is much more deployments then what you described in previous comment. 

Manual promotion here, might be acceptable alternative.

**Comment by adnanrahic** [comment]
Added auto promotion only if branches are `master` or `develop`. Other branches need to be manually promoted.

**Comment by adnanrahic** [comment]
I've decided to drop the staging deployment promotion altogether.
